stages:
  - build
  - deploy

variables:
  PROJECT_NAME: ${CI_PROJECT_NAME}
  PROJECT_GROUP_NAME: ${CI_PROJECT_NAMESPACE}
  DOCKER_IP_TEST_SERVER: "10.171.54.98"
  GITLAB_IP: "123.57.8.180"

serve-book:
  stage: build
  script:
    - cd book
    - rm -rf _book/
    - rm -rf node_modules/
    - gitbook install
    - gitbook build
    - cd ..
    - rm -rf target
    - cp -R docker target
    - mv book/_book target/
    - cd target
    - docker build -t registry-internal.cn-beijing.aliyuncs.com/htouhui/$PROJECT_NAME:$CI_BUILD_REF_SLUG .
    - docker stop $PROJECT_NAME-$CI_BUILD_REF_SLUG || true
    - docker rm -f $PROJECT_NAME-$CI_BUILD_REF_SLUG || true
    - docker run -d -p 4000:80 --name $PROJECT_NAME-$CI_BUILD_REF_SLUG -t registry-internal.cn-beijing.aliyuncs.com/htouhui/$PROJECT_NAME:$CI_BUILD_REF_SLUG

publish_book:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  when: manual
  script:
    - cd book
    - gitbook install
    - gitbook build
    - ossutil cp -r -f _book oss://htouhui-dev-docs/docs